# chapter1_fodoSS_solution.jl
# Auto-generated by chapter1_straight_fodo_solution.ipynb.

K_ss = 0.3519574526492866
kQFSS = 0.35195745264928663
kQDSS = -0.35195745264928646

straight_twiss_x = (beta=27.2059882001124, alpha=-2.402490365720772)
straight_twiss_y = (beta=4.960914114526318, alpha=0.48460555713271297)
reverse_straight_twiss_x = (beta=27.2059882001124, alpha=-2.402490365720772)
reverse_straight_twiss_y = (beta=4.9609141145263225, alpha=0.4846055571327126)
