# Reverse Chapter 1: match the reverse arc FODO cell to 90 degrees.

using SciBmad
using GTPSA
using DifferentiationInterface
import DifferentiationInterface as DI
using LinearAlgebra
using Printf

const tutorial_root = normpath(joinpath(@__DIR__, "..", ".."))

const L_quad = 0.5
const D1_len = 0.609
const D2_len = 1.241
const B_len = 6.86
const B_angle = pi / 132

const species_ref = Species("electron")
const E_ref = 18e9

D1() = Drift(L=D1_len)
D2() = Drift(L=D2_len)
B() = SBend(L=B_len, angle=B_angle)

function build_reverse_arc_fodo(kqf, kqd)
    return Beamline(
        [
            Quadrupole(L=L_quad, Kn1=kqf), D2(), B(), D1(),
            Quadrupole(L=L_quad, Kn1=kqd), D2(), B(), D1(),
        ];
        species_ref=species_ref,
        E_ref=E_ref,
    )
end

function track_a_particle(v0, beamline)
    v = similar(v0)
    v .= v0
    bunch = Bunch(v; species=beamline.species_ref, R_ref=beamline.R_ref)
    track!(bunch, beamline)
    return copy(bunch.coords.v)
end

function linear_map(beamline; x0=zeros(6))
    prep = DI.prepare_jacobian(
        track_a_particle,
        AutoGTPSA(),
        x0,
        DI.Constant(beamline),
    )
    return DI.jacobian(
        track_a_particle,
        prep,
        AutoGTPSA(),
        x0,
        DI.Constant(beamline),
    )
end

function stable_phase_advance(M2)
    cos_mu = clamp(0.5 * tr(M2), -1.0, 1.0)
    return acos(cos_mu)
end

function phase_residual(k)
    M = linear_map(build_reverse_arc_fodo(k[1], k[2]))
    mu_x = stable_phase_advance(M[1:2, 1:2])
    mu_y = stable_phase_advance(M[3:4, 3:4])
    return [mu_x - pi / 2, mu_y - pi / 2]
end

function residual_jacobian(f, x; fd_step=1e-6)
    r0 = f(x)
    J = zeros(length(r0), length(x))
    for j in eachindex(x)
        xp = copy(x)
        xm = copy(x)
        xp[j] += fd_step
        xm[j] -= fd_step
        J[:, j] = (f(xp) - f(xm)) / (2fd_step)
    end
    return J
end

function damped_least_squares(f, x0; maxiter=40, tol=1e-12, lambda0=1e-3)
    x = copy(x0)
    lambda = lambda0

    for iter in 1:maxiter
        r = f(x)
        merit_now = sum(abs2, r)
        J = residual_jacobian(f, x)
        step = -(J' * J + lambda * I) \ (J' * r)
        trial = x + step
        merit_trial = sum(abs2, f(trial))

        @printf(
            "iter %2d  merit = %.6e  step = %.3e  lambda = %.3e\n",
            iter, merit_now, norm(step), lambda,
        )

        if merit_trial < merit_now
            x = trial
            lambda /= 10
        else
            lambda *= 10
        end

        if norm(r) < tol || norm(step) < tol
            break
        end
    end
    return x
end

k_start = [0.4, -0.4]
k_reverse = damped_least_squares(phase_residual, k_start)
kQF_arc_R, kQD_arc_R = k_reverse

M_reverse = linear_map(build_reverse_arc_fodo(kQF_arc_R, kQD_arc_R))
mu_x = stable_phase_advance(M_reverse[1:2, 1:2])
mu_y = stable_phase_advance(M_reverse[3:4, 3:4])

println("\nOptimized reverse arc FODO:")
@printf("  kQF_arc_R = %.15f\n", kQF_arc_R)
@printf("  kQD_arc_R = %.15f\n", kQD_arc_R)
@printf("  mu_x      = %.12f deg\n", rad2deg(mu_x))
@printf("  mu_y      = %.12f deg\n", rad2deg(mu_y))
println("  final residual = ", phase_residual(k_reverse))

solution_text = """
# chapter1_fodoR_solution.jl
# Auto-generated by reverse_chapter1_fodo.jl.

kQF_arc_R = $(repr(kQF_arc_R))
kQD_arc_R = $(repr(kQD_arc_R))
"""

solution_path = joinpath(tutorial_root, "lattices", "chapter_1", "chapter1_fodoR_solution.jl")
mkpath(dirname(solution_path))
write(solution_path, solution_text)
println("\nWrote ", solution_path)
