# chapter6_IR_solution.jl
# Auto-generated by chapter6_exercise4_rebuild_full_ir.jl.
#
# Final interaction-region strengths. QEF values are fixed by the upstream
# low-beta match. QER values include the final full-line rematch to the
# downstream periodic reverse-straight solution.

K_QEF1 = 0.4727712663110847
K_QEF2 = -0.11238277518297729
K_QEF3 = 0.10922540622890103
K_QEF4 = -0.22417037885854876

K_QER1 = -0.0030155854381347
K_QER2 = -0.06225739205958047
K_QER3 = 0.23645705696302452
K_QER4 = -0.23188129495819723
