# chapter6_IR_solution.jl
# Auto-generated by chapter6_exercise4_rebuild_full_ir.jl.
#
# Final interaction-region strengths. QEF values are fixed by the upstream
# low-beta match. QER values include the final full-line rematch to the
# downstream periodic reverse-straight solution.

K_QEF1 = 0.47277126631107236
K_QEF2 = -0.1123827751829804
K_QEF3 = 0.10922540622890102
K_QEF4 = -0.22417037885854865

K_QER1 = -0.003015585438180109
K_QER2 = -0.06225739205955414
K_QER3 = 0.2364570569630243
K_QER4 = -0.23188129495819773
