# chapter6_IPF_solution.jl
# Auto-generated by chapter6_exercise1_match_ipf.jl.
#
# Optimized forward IR quadrupole strengths. These values match the forward
# straight-section periodic Twiss solution to the low-beta target at IP6.

K_QEF1 = 0.4727712663110847
K_QEF2 = -0.11238277518297729
K_QEF3 = 0.10922540622890103
K_QEF4 = -0.22417037885854876
