# Chapter 6, Exercise 4:
# Load the independently matched IPF and IPR strengths, rebuild the full IR, and rematch its downstream end to the periodic reverse-straight solution.

include(joinpath(@__DIR__, "..", "chapter6_matching_common.jl"))

const tutorial_root = normpath(joinpath(@__DIR__, "..", "..", ".."))
include(joinpath(tutorial_root, "lattices", "chapter_6", "chapter6_IPF_solution.jl"))
include(joinpath(tutorial_root, "lattices", "chapter_6", "chapter6_IPR_solution.jl"))

const K_IPF_FIXED = [K_QEF1, K_QEF2, K_QEF3, K_QEF4]
const K_IPR_START = [K_QER1, K_QER2, K_QER3, K_QER4]

function ipf_elements(k)
    return [
        Quadrupole(name="QEF1", L=0.5, Kn1=k[1]), D1(), DB(), D2(),
        Quadrupole(name="QEF2", L=0.5, Kn1=k[2]), D1(), DB(), D2(),
        Drift(name="DEF1", L=20.46),
        Quadrupole(name="QEF3", L=1.6, Kn1=k[3]),
        Drift(name="DEF2", L=3.76),
        Quadrupole(name="QEF4", L=1.2, Kn1=k[4]),
        Drift(name="DEF3", L=5.8),
        IP6(),
    ]
end

function ipr_elements(k; include_ip_marker=false)
    # The full IR already contains IP6 at the end of IPF, so the second copy of the zero-length marker is omitted when the two halves are connected.
    elements = [
        Drift(name="DER3", L=5.3),
        Quadrupole(name="QER4", L=1.8, Kn1=k[4]),
        Drift(name="DER2", L=0.5),
        Quadrupole(name="QER3", L=1.4, Kn1=k[3]),
        Drift(name="DER1", L=23.82),
        Quadrupole(name="QER2", L=0.5, Kn1=k[2]), D2(), DB(), D1(),
        Quadrupole(name="QER1", L=0.5, Kn1=k[1]), D2(), DB(), D1(),
    ]
    return include_ip_marker ? vcat([IP6()], elements) : elements
end

function build_full_IR(k_ipr)
    return Beamline(
        vcat(ipf_elements(K_IPF_FIXED), ipr_elements(k_ipr));
        species_ref=species_ref,
        E_ref=E_ref,
    )
end

input_a, input_b = periodic_twiss(build_forward_straight_fodo())
target_end_a, target_end_b = periodic_twiss(build_reverse_straight_fodo())

function full_ir_end_twiss(k_ipr)
    Mx, My = transverse_blocks(transfer_matrix_gtpsa(build_full_IR(k_ipr)))
    return propagate_twiss(input_a, Mx), propagate_twiss(input_b, My)
end

function full_ir_end_twiss_with_knobs(k_ipr, descriptor, dk)
    Mx, My = transverse_blocks(linear_map_with_descriptor(build_full_IR(k_ipr .+ dk), descriptor))
    return propagate_twiss(input_a, Mx), propagate_twiss(input_b, My)
end

function full_ir_residual_with_knobs(k_ipr, descriptor, dk)
    output_a, output_b = full_ir_end_twiss_with_knobs(k_ipr, descriptor, dk)
    return [
        (output_a.beta - target_end_a.beta) / target_end_a.beta,
        output_a.alpha - target_end_a.alpha,
        (output_b.beta - target_end_b.beta) / target_end_b.beta,
        output_b.alpha - target_end_b.alpha,
    ]
end

function full_ir_residual(k_ipr)
    output_a, output_b = full_ir_end_twiss(k_ipr)
    return [
        (output_a.beta - target_end_a.beta) / target_end_a.beta,
        output_a.alpha - target_end_a.alpha,
        (output_b.beta - target_end_b.beta) / target_end_b.beta,
        output_b.alpha - target_end_b.alpha,
    ]
end

function full_ir_residual_jacobian(k_ipr)
    descriptor = Descriptor(6, 2, 4, 1)
    dk = params(descriptor)
    residual = full_ir_residual_with_knobs(k_ipr, descriptor, dk)
    return vcat((parameter_gradient(r)' for r in residual)...)
end

println("Loaded independently matched IPF and IPR strengths.")
println("Initial full-IR downstream residual = ", full_ir_residual(K_IPR_START))

# Only the downstream QER strengths are varied in the final full-line match.
K_IPR_FINAL = damped_least_squares(full_ir_residual, K_IPR_START; jacobian=full_ir_residual_jacobian)
K_QER1_FINAL, K_QER2_FINAL, K_QER3_FINAL, K_QER4_FINAL = K_IPR_FINAL

final_a, final_b = full_ir_end_twiss(K_IPR_FINAL)
println("\nFinal full-IR downstream residual = ", full_ir_residual(K_IPR_FINAL))
@printf("  downstream beta_a = %.12f, alpha_a = %.12f\n", final_a.beta, final_a.alpha)
@printf("  downstream beta_b = %.12f, alpha_b = %.12f\n", final_b.beta, final_b.alpha)

# Check that the fixed IPF still reaches the requested low-beta waist at IP6.
ipf_only = Beamline(ipf_elements(K_IPF_FIXED); species_ref=species_ref, E_ref=E_ref)
Mx_ipf, My_ipf = transverse_blocks(transfer_matrix_gtpsa(ipf_only))
ip_a = propagate_twiss(input_a, Mx_ipf)
ip_b = propagate_twiss(input_b, My_ipf)
@printf("\nIP6 beta_a = %.12f, alpha_a = %.3e\n", ip_a.beta, ip_a.alpha)
@printf("IP6 beta_b = %.12f, alpha_b = %.3e\n", ip_b.beta, ip_b.alpha)

solution_text = """
# chapter6_IR_solution.jl
# Auto-generated by chapter6_exercise4_rebuild_full_ir.jl.
#
# Final interaction-region strengths. QEF values are fixed by the upstream
# low-beta match. QER values include the final full-line rematch to the
# downstream periodic reverse-straight solution.

K_QEF1 = $(repr(K_QEF1))
K_QEF2 = $(repr(K_QEF2))
K_QEF3 = $(repr(K_QEF3))
K_QEF4 = $(repr(K_QEF4))

K_QER1 = $(repr(K_QER1_FINAL))
K_QER2 = $(repr(K_QER2_FINAL))
K_QER3 = $(repr(K_QER3_FINAL))
K_QER4 = $(repr(K_QER4_FINAL))
"""

solution_path = joinpath(tutorial_root, "lattices", "chapter_6", "chapter6_IR_solution.jl")
mkpath(dirname(solution_path))
write(solution_path, solution_text)
println("\nWrote ", solution_path)
