# Chapter 6, Exercise 3:
# Match the downstream interaction-region line backwards from the straight
# section to IP6.

include(joinpath(@__DIR__, "..", "chapter6_matching_common.jl"))

const tutorial_root = normpath(joinpath(@__DIR__, "..", "..", ".."))

function build_IPR(k)
    # IPR is listed in the physical beam direction, starting at IP6 and ending
    # in the downstream reverse straight section.
    return Beamline(
        [
            IP6(),
            Drift(name="DER3", L=5.3),
            Quadrupole(name="QER4", L=1.8, Kn1=k[4]),
            Drift(name="DER2", L=0.5),
            Quadrupole(name="QER3", L=1.4, Kn1=k[3]),
            Drift(name="DER1", L=23.82),
            Quadrupole(name="QER2", L=0.5, Kn1=k[2]), D2(), DB(), D1(),
            Quadrupole(name="QER1", L=0.5, Kn1=k[1]), D2(), DB(), D1(),
        ];
        species_ref=species_ref,
        E_ref=E_ref,
    )
end

downstream_a, downstream_b = periodic_twiss(build_reverse_straight_fodo())

function ipr_ip_twiss(k)
    # Backward matching is a calculation: use the inverse transfer matrices to
    # propagate the known downstream periodic Twiss parameters back to IP6.
    Mx, My = transverse_blocks(transfer_matrix_gtpsa(build_IPR(k)))
    return propagate_twiss(downstream_a, inv(Mx)), propagate_twiss(downstream_b, inv(My))
end

function ipr_ip_twiss_with_knobs(k, descriptor, dk)
    Mx, My = transverse_blocks(linear_map_with_descriptor(build_IPR(k .+ dk), descriptor))
    return propagate_twiss(downstream_a, inv(concrete_matrix(Mx))),
           propagate_twiss(downstream_b, inv(concrete_matrix(My)))
end

function ipr_residual_with_knobs(k, descriptor, dk)
    output_a, output_b = ipr_ip_twiss_with_knobs(k, descriptor, dk)
    return normalized_ip_residual(output_a, output_b)
end

function ipr_residual(k)
    output_a, output_b = ipr_ip_twiss(k)
    return normalized_ip_residual(output_a, output_b)
end

function ipr_residual_jacobian(k)
    descriptor = Descriptor(6, 2, 4, 1)
    dk = params(descriptor)
    residual = ipr_residual_with_knobs(k, descriptor, dk)
    return vcat((parameter_gradient(r)' for r in residual)...)
end

# This low-beta line has several local minima. Starting from the independently
# matched IPF strengths reliably reaches the useful IPR solution.
K_start = [
    0.472771266311072,
    -0.112382775182980,
    0.109225406228901,
    -0.224170378858549,
]
K_IPR = damped_least_squares(ipr_residual, K_start; jacobian=ipr_residual_jacobian)
K_QER1, K_QER2, K_QER3, K_QER4 = K_IPR

matched_a, matched_b = ipr_ip_twiss(K_IPR)
Mx_matched, My_matched = transverse_blocks(transfer_matrix_gtpsa(build_IPR(K_IPR)))
forward_end_a = propagate_twiss(target_a, Mx_matched)
forward_end_b = propagate_twiss(target_b, My_matched)

println("\nReverse straight-section periodic Twiss at the IPR downstream end:")
@printf("  beta_a = %.12f, alpha_a = %.12f\n", downstream_a.beta, downstream_a.alpha)
@printf("  beta_b = %.12f, alpha_b = %.12f\n", downstream_b.beta, downstream_b.alpha)

println("\nOptimized IPR quadrupole strengths:")
@printf("  K_QER1 = %.15f\n", K_QER1)
@printf("  K_QER2 = %.15f\n", K_QER2)
@printf("  K_QER3 = %.15f\n", K_QER3)
@printf("  K_QER4 = %.15f\n", K_QER4)

println("\nBackward-matched Twiss at IP6:")
@printf("  beta_a = %.12f, alpha_a = %.12e\n", matched_a.beta, matched_a.alpha)
@printf("  beta_b = %.12f, alpha_b = %.12e\n", matched_b.beta, matched_b.alpha)
println("  final residual = ", ipr_residual(K_IPR))

println("\nForward check at the IPR downstream end:")
@printf("  beta_a = %.12f, alpha_a = %.12f\n", forward_end_a.beta, forward_end_a.alpha)
@printf("  beta_b = %.12f, alpha_b = %.12f\n", forward_end_b.beta, forward_end_b.alpha)

solution_text = """
# chapter6_IPR_solution.jl
# Auto-generated by chapter6_exercise3_match_ipr.jl.
#
# Optimized downstream IR quadrupole strengths. These values match the IP6
# low-beta target forward into the reverse straight-section periodic solution.

K_QER1 = $(repr(K_QER1))
K_QER2 = $(repr(K_QER2))
K_QER3 = $(repr(K_QER3))
K_QER4 = $(repr(K_QER4))
"""

solution_path = joinpath(tutorial_root, "lattices", "chapter_6", "chapter6_IPR_solution.jl")
mkpath(dirname(solution_path))
write(solution_path, solution_text)
println("\nWrote ", solution_path)
