# Chapter 6, Exercise 1:
# Match the forward interaction-region line from the straight section to IP6.

include(joinpath(@__DIR__, "..", "chapter6_matching_common.jl"))

const tutorial_root = normpath(joinpath(@__DIR__, "..", "..", ".."))

function build_IPF(k)
    # The first two quadrupoles replace ordinary straight-section FODO
    # quadrupoles. The final pair creates the low-beta waist at IP6.
    return Beamline(
        [
            Quadrupole(name="QEF1", L=0.5, Kn1=k[1]), D1(), DB(), D2(),
            Quadrupole(name="QEF2", L=0.5, Kn1=k[2]), D1(), DB(), D2(),
            Drift(name="DEF1", L=20.46),
            Quadrupole(name="QEF3", L=1.6, Kn1=k[3]),
            Drift(name="DEF2", L=3.76),
            Quadrupole(name="QEF4", L=1.2, Kn1=k[4]),
            Drift(name="DEF3", L=5.8),
            IP6(),
        ];
        species_ref=species_ref,
        E_ref=E_ref,
    )
end

input_a, input_b = periodic_twiss(build_forward_straight_fodo())

function ipf_end_twiss(k)
    # Propagate the known periodic straight-section Twiss parameters to IP6.
    Mx, My = transverse_blocks(transfer_matrix_gtpsa(build_IPF(k)))
    return propagate_twiss(input_a, Mx), propagate_twiss(input_b, My)
end

function ipf_end_twiss_with_knobs(k, descriptor, dk)
    Mx, My = transverse_blocks(linear_map_with_descriptor(build_IPF(k .+ dk), descriptor))
    return propagate_twiss(input_a, Mx), propagate_twiss(input_b, My)
end

function ipf_residual_with_knobs(k, descriptor, dk)
    output_a, output_b = ipf_end_twiss_with_knobs(k, descriptor, dk)
    return normalized_ip_residual(output_a, output_b)
end

function ipf_residual(k)
    # Four independently varied quadrupoles satisfy the four IP Twiss targets.
    output_a, output_b = ipf_end_twiss(k)
    return normalized_ip_residual(output_a, output_b)
end

function ipf_residual_jacobian(k)
    descriptor = Descriptor(6, 2, 4, 1)
    dk = params(descriptor)
    residual = ipf_residual_with_knobs(k, descriptor, dk)
    return vcat((parameter_gradient(r)' for r in residual)...)
end

K_start = [K_ss, -K_ss, K_ss, -K_ss]
K_IPF = damped_least_squares(ipf_residual, K_start; jacobian=ipf_residual_jacobian)
K_QEF1, K_QEF2, K_QEF3, K_QEF4 = K_IPF

matched_a, matched_b = ipf_end_twiss(K_IPF)

println("\nForward straight-section periodic Twiss at the IPF entrance:")
@printf("  beta_a = %.12f, alpha_a = %.12f\n", input_a.beta, input_a.alpha)
@printf("  beta_b = %.12f, alpha_b = %.12f\n", input_b.beta, input_b.alpha)

println("\nOptimized IPF quadrupole strengths:")
@printf("  K_QEF1 = %.15f\n", K_QEF1)
@printf("  K_QEF2 = %.15f\n", K_QEF2)
@printf("  K_QEF3 = %.15f\n", K_QEF3)
@printf("  K_QEF4 = %.15f\n", K_QEF4)

println("\nMatched Twiss at IP6:")
@printf("  beta_a = %.12f, alpha_a = %.12e\n", matched_a.beta, matched_a.alpha)
@printf("  beta_b = %.12f, alpha_b = %.12e\n", matched_b.beta, matched_b.alpha)
println("  final residual = ", ipf_residual(K_IPF))

solution_text = """
# chapter6_IPF_solution.jl
# Auto-generated by chapter6_exercise1_match_ipf.jl.
#
# Optimized forward IR quadrupole strengths. These values match the forward
# straight-section periodic Twiss solution to the low-beta target at IP6.

K_QEF1 = $(repr(K_QEF1))
K_QEF2 = $(repr(K_QEF2))
K_QEF3 = $(repr(K_QEF3))
K_QEF4 = $(repr(K_QEF4))
"""

solution_path = joinpath(tutorial_root, "lattices", "chapter_6", "chapter6_IPF_solution.jl")
mkpath(dirname(solution_path))
write(solution_path, solution_text)
println("\nWrote ", solution_path)
