# chapter2_dispsupR_solution.jl
# Auto-generated by reverse_chapter2_dispersion_suppressor.jl.

kQF_arc_R = 0.3126646961206135
kQD_arc_R = -0.3127984815244765

kQFR1 = 0.3129099157537034
kQDR1 = -0.314637911076659
