# chapter2_dispsupR_solution.jl
# Auto-generated by reverse_chapter2_dispersion_suppressor.jl.

kQF_arc_R = 0.31266469612061343
kQD_arc_R = -0.3127984815244764

kQFR1 = 0.3129099157537042
kQDR1 = -0.3146379110766582
