# Reverse Chapter 2: match the reverse dispersion suppressor to zero dispersion.

using SciBmad
using GTPSA
using DifferentiationInterface
import DifferentiationInterface as DI
using LinearAlgebra
using Printf

const tutorial_root = normpath(joinpath(@__DIR__, "..", ".."))
const chapter1_solution = joinpath(tutorial_root, "lattices", "chapter_1", "chapter1_fodoR_solution.jl")

isfile(chapter1_solution) ||
    error("Run reverse_chapter1_fodo.jl first.")
include(chapter1_solution)

const L_quad = 0.5
const D1_len = 0.609
const D2_len = 1.241
const B_len = 6.86
const B_angle = pi / 132
const BH_angle = B_angle / 2

const species_ref = Species("electron")
const E_ref = 18e9

D1() = Drift(L=D1_len)
D2() = Drift(L=D2_len)
B() = SBend(L=B_len, angle=B_angle)
BH() = SBend(L=B_len, angle=BH_angle)
QF_arc_R() = Quadrupole(L=L_quad, Kn1=kQF_arc_R)
QD_arc_R() = Quadrupole(L=L_quad, Kn1=kQD_arc_R)

function build_reverse_arc_fodo()
    return Beamline(
        [
            QF_arc_R(), D2(), B(), D1(),
            QD_arc_R(), D2(), B(), D1(),
        ];
        species_ref=species_ref,
        E_ref=E_ref,
    )
end

function build_reverse_suppressor(kqfr1, kqdr1)
    return Beamline(
        [
            QF_arc_R(), D2(), BH(), D1(),
            QD_arc_R(), D2(), BH(), D1(),
            Quadrupole(L=L_quad, Kn1=kqfr1), D2(), BH(), D1(),
            Quadrupole(L=L_quad, Kn1=kqdr1), D2(), BH(), D1(),
        ];
        species_ref=species_ref,
        E_ref=E_ref,
    )
end

function track_a_particle(v0, beamline)
    v = similar(v0)
    v .= v0
    bunch = Bunch(v; species=beamline.species_ref, R_ref=beamline.R_ref)
    track!(bunch, beamline)
    return copy(bunch.coords.v)
end

function linear_map(beamline; x0=zeros(6))
    prep = DI.prepare_jacobian(
        track_a_particle,
        AutoGTPSA(),
        x0,
        DI.Constant(beamline),
    )
    return DI.jacobian(
        track_a_particle,
        prep,
        AutoGTPSA(),
        x0,
        DI.Constant(beamline),
    )
end

function periodic_dispersion_from_map(M)
    A = M[1:2, 1:2]
    drive = M[1:2, 6]
    D = (I - A) \ drive
    return D
end

function transport_dispersion(M, D0)
    return M[1:2, 1:2] * D0 + M[1:2, 6]
end

M_arc_R = linear_map(build_reverse_arc_fodo())
D_arc_R = periodic_dispersion_from_map(M_arc_R)

function suppressor_residual(k)
    M = linear_map(build_reverse_suppressor(k[1], k[2]))
    return transport_dispersion(M, D_arc_R)
end

function residual_jacobian(f, x; fd_step=1e-6)
    r0 = f(x)
    J = zeros(length(r0), length(x))
    for j in eachindex(x)
        xp = copy(x)
        xm = copy(x)
        xp[j] += fd_step
        xm[j] -= fd_step
        J[:, j] = (f(xp) - f(xm)) / (2fd_step)
    end
    return J
end

function damped_least_squares(f, x0; maxiter=40, tol=1e-12, lambda0=1e-3)
    x = copy(x0)
    lambda = lambda0

    for iter in 1:maxiter
        r = f(x)
        merit_now = sum(abs2, r)
        J = residual_jacobian(f, x)
        step = -(J' * J + lambda * I) \ (J' * r)
        trial = x + step
        merit_trial = sum(abs2, f(trial))

        @printf(
            "iter %2d  merit = %.6e  step = %.3e  lambda = %.3e\n",
            iter, merit_now, norm(step), lambda,
        )

        if merit_trial < merit_now
            x = trial
            lambda /= 10
        else
            lambda *= 10
        end

        if norm(r) < tol || norm(step) < tol
            break
        end
    end
    return x
end

k_start = [kQF_arc_R, kQD_arc_R]
k_suppressor_R = damped_least_squares(suppressor_residual, k_start)
kQFR1, kQDR1 = k_suppressor_R

println("\nPeriodic reverse-arc dispersion at suppressor entrance:")
@printf("  eta_x  = %+.12e m\n", D_arc_R[1])
@printf("  eta_x' = %+.12e\n", D_arc_R[2])

println("\nOptimized reverse dispersion suppressor:")
@printf("  kQFR1 = %.15f\n", kQFR1)
@printf("  kQDR1 = %.15f\n", kQDR1)
println("  final residual [eta_x, eta_x'] = ", suppressor_residual(k_suppressor_R))

solution_text = """
# chapter2_dispsupR_solution.jl
# Auto-generated by reverse_chapter2_dispersion_suppressor.jl.

kQF_arc_R = $(repr(kQF_arc_R))
kQD_arc_R = $(repr(kQD_arc_R))

kQFR1 = $(repr(kQFR1))
kQDR1 = $(repr(kQDR1))
"""

solution_path = joinpath(tutorial_root, "lattices", "chapter_2", "chapter2_dispsupR_solution.jl")
mkpath(dirname(solution_path))
write(solution_path, solution_text)
println("\nWrote ", solution_path)
