# chapter3_mSSR_solution.jl
# Auto-generated by reverse_chapter3_twiss_matching.jl.

K_QFR2 = 0.35611249694112124
K_QDR2 = -0.3450496534173547
K_QFR3 = 0.37870602472266757
K_QDR3 = -0.35073218248126775
