# chapter3_mSSR_solution.jl
# Auto-generated by reverse_chapter3_twiss_matching.jl.

K_QFR2 = 0.35611249694112257
K_QDR2 = -0.34504965341735533
K_QFR3 = 0.3787060247226696
K_QDR3 = -0.3507321824812673
